"""Generate configs/example_{tornionjoki,simojoki,byskealven,morrumsan}.yaml
from the example_baltic.yaml template with per-river WGBAST overrides.

Pragmatic choice (Arc M): reuse the Nemunas-basin fixture shapefile and
reach names verbatim — they're just geometric scaffolding for the IBM
scheduler. What makes each config a WGBAST-river is (a) the simulation
temperature + flow forcing in the per-reach TimeSeriesInputs CSVs
(pre-generated by `_scaffold_wgbast_rivers.py`), (b) the WGBAST-specific
parameters injected into the reaches: `river_name`, `pspc_smolts_per_year`,
and species-level `smolt_min_length`.

This means reach NAMES in the YAML stay Nemunas/Atmata/Minija/... but
their `river_name` attribute (Arc L) and PSPC values (Arc K) are
WGBAST-calibrated. Later refinement (Arc M.4 / Arc 0) can rewrite the
DBF attributes to use real Torne/Simo reach names.

See docs/superpowers/plans/2026-04-20-arc-M-to-Q-expanded.md Arc M.
"""
from __future__ import annotations
from pathlib import Path
import yaml


ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_CFG = ROOT / "configs" / "example_baltic.yaml"


# PSPC distribution across the 9 Nemunas-basin reaches, keyed by WGBAST
# river total (Torne 2.2M / Simo 95k / Byske 180k / Mörrum 60k). Non-natal
# reaches (lagoon, coast) get None.
RIVER_SPECS = {
    "example_tornionjoki": {
        "stem": "TornionjokiExample",
        "latitude": 65.85,
        "river_name": "Tornionjoki",
        "smolt_min_length": 14.0,
        # Distribute Torne's 2.2M across the 9 baltic-basin reaches
        # proportionally to Anttila-2008 reach-quality pattern:
        # main channel (Nemunas) 40%, main corridor (Atmata) 20%,
        # main tributary (Minija) 18%, small tributaries 15% total,
        # estuary/coast non-natal.
        "pspc_by_reach": {
            "Nemunas": 880000,
            "Atmata": 440000,
            "Minija": 400000,
            "Sysa": 140000,
            "Skirvyte": 130000,
            "Leite": 105000,
            "Gilija": 105000,
            "CuronianLagoon": None,
            "BalticCoast": None,
        },
    },
    "example_simojoki": {
        "stem": "SimojokiExample",
        "latitude": 65.60,
        "river_name": "Simojoki",
        "smolt_min_length": 14.0,
        # Simo 95k: main channel 50k + secondary 25k + tributaries 20k
        "pspc_by_reach": {
            "Nemunas": 50000,
            "Atmata": 25000,
            "Minija": 20000,
            "Sysa": None,
            "Skirvyte": None,
            "Leite": None,
            "Gilija": None,
            "CuronianLagoon": None,
            "BalticCoast": None,
        },
    },
    "example_byskealven": {
        "stem": "ByskealvenExample",
        "latitude": 64.98,
        "river_name": "Byskealven",
        "smolt_min_length": 13.0,
        # Byske 180k: main 75k + major tribs 60k + minor 45k
        "pspc_by_reach": {
            "Nemunas": 75000,
            "Atmata": 45000,
            "Minija": 35000,
            "Sysa": 12000,
            "Skirvyte": 13000,
            "Leite": None,
            "Gilija": None,
            "CuronianLagoon": None,
            "BalticCoast": None,
        },
    },
    "example_morrumsan": {
        "stem": "MorrumsanExample",
        "latitude": 56.17,
        "river_name": "Morrumsan",
        "smolt_min_length": 11.0,
        # Mörrum 60k: main 30k + tributary 20k + minor 10k
        "pspc_by_reach": {
            "Nemunas": 30000,
            "Atmata": 20000,
            "Minija": 10000,
            "Sysa": None,
            "Skirvyte": None,
            "Leite": None,
            "Gilija": None,
            "CuronianLagoon": None,
            "BalticCoast": None,
        },
    },
}


def generate_config(short_name: str, spec: dict) -> None:
    with open(TEMPLATE_CFG, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    # 1. simulation block
    cfg["simulation"]["start_date"] = "2011-04-01"
    cfg["simulation"]["end_date"] = "2016-03-31"
    cfg["simulation"]["seed"] = 42
    cfg["simulation"]["population_file"] = f"{spec['stem']}-InitialPopulations.csv"
    cfg["simulation"]["adult_arrival_file"] = f"{spec['stem']}-AdultArrivals.csv"
    # Arc L: WGBAST M74 forcing (fires only on rivers in the CSV —
    # Simojoki + Tornionjoki; Byske/Mörrum are no-ops)
    cfg["simulation"]["m74_forcing_csv"] = "data/wgbast/m74_ysfm_series.csv"

    # 2. light.latitude
    cfg["light"]["latitude"] = spec["latitude"]

    # 3. species-level smolt_min_length (WGBAST Skoglund 2024 latitudinal)
    for sp_name, sp_cfg in cfg.get("species", {}).items():
        sp_cfg["smolt_min_length"] = spec["smolt_min_length"]
    if "marine" in cfg:
        cfg["marine"]["smolt_min_length"] = spec["smolt_min_length"]

    # 4. Inject PSPC + river_name into each reach (keeping Nemunas-basin
    #    names and all other parameters verbatim from template).
    for reach_name, reach_cfg in cfg.get("reaches", {}).items():
        pspc = spec["pspc_by_reach"].get(reach_name)
        if pspc is None:
            # Remove any existing PSPC (non-natal for this river)
            reach_cfg.pop("pspc_smolts_per_year", None)
        else:
            reach_cfg["pspc_smolts_per_year"] = pspc
        reach_cfg["river_name"] = spec["river_name"]

    # Write
    out_path = ROOT / "configs" / f"example_{short_name}.yaml"
    total_pspc = sum(p for p in spec["pspc_by_reach"].values() if p)
    header = (
        f"# {spec['river_name']} WGBAST-assessment-ready fixture.\n"
        f"# Generated via scripts/_generate_wgbast_configs.py from example_baltic.yaml\n"
        f"# Latitude: {spec['latitude']}°N; smolt_min_length: {spec['smolt_min_length']} cm\n"
        f"# Fixture: tests/fixtures/{short_name}/\n"
        f"# Plan: docs/superpowers/plans/2026-04-20-arc-M-to-Q-expanded.md Arc M\n"
        f"#\n"
        f"# WGBAST PSPC total: {total_pspc:,} smolts/yr (WGBAST 2026 §3)\n"
        f"# Pragmatic scaffolding: reach NAMES are Nemunas-basin (from template\n"
        f"# shapefile) but each reach carries `river_name: {spec['river_name']}`\n"
        f"# and WGBAST PSPC. Temperature + flow forcing in the per-reach\n"
        f"# TimeSeriesInputs.csv files is latitude-appropriate for {spec['river_name']}.\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
    print(f"[{short_name}] wrote {out_path}")


def main() -> None:
    for short_name, spec in RIVER_SPECS.items():
        generate_config(short_name, spec)


if __name__ == "__main__":
    main()
